# Site settings
title: Proof of concept - Using Firebase in Github page
email: notbenj@gmail.com
description: "Proof of concept - Using Firebase in Github page"
baseurl: "/firebase"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
