# Site settings
title: Jekyll / Firebase in github (using AngularJS)
email: notbenj@gmail.com
description: "Testing BaaS with Github and Jekyll"
baseurl: "/firebase"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
