# Site settings
title: Test Firebase in github
email: notbenj@gmail.com
description: "Testing BaaS with Github and Jekyll"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
